attributes:

  credentials_package:
    value: ''
    label: 'Credentials package'
    description: 'base64 credentials file'
    weight: 20
    type: "file"

  advanced_params_enabled:
    value: false
    label: "Advanced Parameters"
    description: "Enables configuration of advanced parameters"
    weight: 30
    type: "checkbox"

  va_license_file:
    value: ''
    label: "LICENSE FILE"
    description: "license file used to activate VA"
    weight: 35
    type: "file"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  fp_mem:
    value: '1024'
    label: 'FP_MEMORY'
    description: 'defines how much memory is used by VA'
    weight: 40
    type: "text"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  cores_per_port:
    value: '1'
    label: 'CORE_PER_PORT'
    description: 'defines the amount of cores polling each port'
    weight: 40
    type: "text"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  vm_mem:
    value: 'auto'
    label: 'VM_MEMORY'
    description: 'defines the memory available for vms'
    weight: 40
    type: "text"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  va_conf_file:
    value: ''
    label: 'External configuration file for VA'
    description: '(optional) specify external configuration file for starting VA'
    weight: 50
    type: "file"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  ext_pack:
    value: true
    label: 'Use updated external packages'
    description: 'Specify if need to use most uptodate external packages (libvirtd, qemu)'
    weight: 70
    type: "checkbox"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  disable_ipset:
    value: true
    label: 'Disable neutron ipset'
    description: 'Set/unset support for ipset when using security groups'
    weight: 75
    type: "checkbox"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  infos:
    weight: 80
    type: "hidden"
    value: true
    label: "Important notes:"
    description: "Before changing default settings for Virtual Accelerator, please have a look at
                  6WIND's Virtual Accelerator online documentation for applicable values:\n
                    Product description:  http://www.6wind.com/products/6wind-virtual-accelerator/\n
                    User Guide:           http://www.6wind.com/products/6wind-virtual-accelerator/\n"

    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide
