attributes:

  metadata:
    group: 'compute'
    restrictions:
      - condition: "settings:common.libvirt_type.value != 'kvm'"
        message: "KVM needs to be chosen as hypervisor"

  credentials_package:
    value: ''
    label: 'Credentials package'
    description: 'base64 credentials file'
    weight: 20
    type: "file"

  va_license_file:
    value: ''
    label: "License File"
    description: "(optional) license file used to activate VA"
    weight: 30
    type: "file"

  va_version:
    value: 'stable'
    label: 'Product branch'
    description: 'defines the Virtual Accelerator version to be installed (in 1.x format)'
    weight: 32
    type: "text"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.credentials_package.value == ''"
        message: "Provide a credentials package"

  mellanox_support:
    value: false
    label: "Enable Mellanox NICs support"
    description: "Installs 6WIND Virtual Accelerator addon to support Mellanox NICs"
    weight: 35
    type: "checkbox"

  advanced_params_enabled:
    value: false
    label: "Advanced Parameters"
    description: "Enables configuration of advanced parameters"
    weight: 36
    type: "checkbox"

  fp_mem:
    value: 'auto'
    label: 'FP_MEMORY'
    description: 'defines the amount of memory used by Virtual Accelerator (in MB)'
    weight: 40
    type: "text"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  vm_mem:
    value: 'auto'
    label: 'VM_MEMORY'
    description: 'defines the amount of memory available for accelerated vms (in MB)'
    weight: 40
    type: "text"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  va_conf_file:
    value: ''
    label: 'External configuration file for VA'
    description: '(optional) specify external configuration file for starting VA'
    weight: 50
    type: "file"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  ext_pack:
    value: true
    label: 'Use updated external packages'
    description: 'Specify if need to use most uptodate external packages (libvirtd, qemu)'
    weight: 70
    type: "checkbox"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  enable_host_cpu:
    value: false
    label: 'Host cpu emulation for guests'
    description: 'Set/unset host cpu emulation for guests'
    weight: 75
    type: "checkbox"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  disable_ipset:
    value: false
    label: 'Disable neutron ipset'
    description: 'Set/unset support for ipset when using security groups'
    weight: 80
    type: "checkbox"
    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide

  infos:
    weight: 90
    type: "hidden"
    value: true
    label: "Important notes:"
    description: "Before changing default settings for Virtual Accelerator, please have a look at
                  6WIND's Virtual Accelerator online documentation for applicable values:\n
                    Product description:  http://www.6wind.com/products/6wind-virtual-accelerator/\n
                    User Guide:           http://www.6wind.com/products/6wind-virtual-accelerator/\n"

    restrictions:
      - condition: "settings:6wind-virtual-accelerator.advanced_params_enabled.value == false"
        action: hide
